backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    preview_path: pages/index/{{slug}}
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index/index-page"}
          - {label: Banners, name: banners, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Small Text, name: smallText, widget: text}, {label: Title, name: title, widget: text}]}
          - {label: "We are", name: weare, widget:  object, fields: [{label: Text, name: text, widget: markdown}, {label: Image, name: image, widget: image} ]}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Why choose us?", name: whychooseus, widget: object, fields: [{label: SubTitle, name: subTitle, widget: string}, {label: Title, name: title, widget: string}, {label: "Left Side", name: leftside, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}, {label: "Right Side", name: rightside, widget: object, fields: [{label: Image, name: image, widget: image}]}]}
          - {label: "Our Vision", name: ourvision, widget: object, fields: [{label: SubTitle, name: subTitle, widget: string}, {label: Title, name: title, widget: string}, {label: "Left Side", name: leftside, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}, {label: "Right Side", name: rightside, widget: object, fields: [{label: Image, name: image, widget: image}]}]}

local_backend: true